services:
  - type: web
    name: movie-conversation-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8183840071:AAEp6qMFHZa_vplMn309Lao-iiojFYY4QKk
      - key: ADMIN_ID
        value: "7477843431"
      - key: PORT
        value: "10000"
